#define a Kubernetes Deployment and Service to run
#your book-catelog app in a Kubernetes cluster. The app will be exposed on port 80 via a nodeport.
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catelog
  template:
    metadata:
      labels:
        app: book-catelog
    spec:
      containers:
      - name: book-catelog
        image: book-catelog:1
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week06_5gcb_user:CqZo6hkVFgHL7I5lyhjFhRGX4PcKayfN@dpg-crejge3v2p9s73cvq2t0-a.oregon-postgres.render.com/week06_5gcb"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catelog
spec:
  selector:
    app: book-catelog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
